#ifndef SPIELDA_GAME_COMPONENTS_TAGS_ATTACHMENT_HPP
#define SPIELDA_GAME_COMPONENTS_TAGS_ATTACHMENT_HPP

namespace spielda::tags
{

struct Attachment
{
};

} // spielda::tags

#endif //SPIELDA_GAME_COMPONENTS_TAGS_ATTACHMENT_HPP
